2022-01-18 17:12:01.204 [info] <0.44.0> Application lager started on node nonode@nohost
2022-01-18 17:12:01.210 [info] <0.44.0> Application worker_pool started on node nonode@nohost
2022-01-18 17:12:01.216 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2022-01-18 17:12:01.216 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',map,2,[{file,"lib/enum.ex"},{line,3383}]},{'Elixir.KafkaEx.Server0P10AndLater',kafka_server_init,1,[{file,"lib/kafka_ex/server_0_p_10_and_later.ex"},{line,96}]},{gen_server,init_it,2,[{file,"gen_server...."},...]},...]},...} in application_master:init/4 line 138
2022-01-18 17:12:01.217 [info] <0.44.0> Application kafka_ex exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',map,2,[{file,"lib/enum.ex"},{line,3383}]},{'Elixir.KafkaEx.Server0P10AndLater',kafka_server_init,1,[{file,"lib/kafka_ex/server_0_p_10_and_later.ex"},{line,96}]},{gen_server,init_it,2,[{file,"gen_server...."},...]},...]},...}
2022-01-18 17:12:01.219 [info] <0.44.0> Application worker_pool exited with reason: stopped
